# Generated by Django 4.2 on 2024-08-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_alter_sevices_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='sp_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='No descriptions.')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
