# Generated by Django 4.2 on 2024-08-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_sp_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sp_services',
            new_name='sservices',
        ),
    ]
