# Generated by Django 4.2 on 2024-08-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_rename_sp_services_sservices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sservices',
            old_name='description',
            new_name='descrip',
        ),
    ]
