# Generated by Django 4.2 on 2024-08-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_rename_description_sservices_descrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='askes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
