# Generated by Django 4.2 on 2024-08-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_askes'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skil', models.CharField(max_length=100)),
                ('bio', models.TextField(default='')),
                ('prof', models.ImageField(default='Default_trainer.png', upload_to='trainer')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
