# Generated by Django 4.2 on 2024-08-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='vijegi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusf', models.TextField(default='')),
                ('statust', models.TextField(default='')),
            ],
        ),
    ]
