# Generated by Django 4.2 on 2024-08-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_vijegi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vijegi',
            old_name='statusf',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='vijegi',
            name='statust',
        ),
        migrations.AddField(
            model_name='vijegi',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
