# Generated by Django 4.2 on 2024-08-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
