# Generated by Django 4.2 on 2024-08-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_price_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='vijegi',
            field=models.ManyToManyField(to='root.vijegi'),
        ),
    ]
