# Generated by Django 4.2 on 2024-08-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_price_vijegi'),
    ]

    operations = [
        migrations.CreateModel(
            name='vijegif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='vijegit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='vijegi',
        ),
        migrations.DeleteModel(
            name='vijegi',
        ),
        migrations.AddField(
            model_name='price',
            name='vf',
            field=models.ManyToManyField(to='root.vijegif'),
        ),
        migrations.AddField(
            model_name='price',
            name='vt',
            field=models.ManyToManyField(to='root.vijegit'),
        ),
    ]
